### ISSUE TITLE
Error when having table names with capital letters

### ISSUE THREAD

**Issue by Kaaaaii** [Paultje52/better-mysql#3]
I resolved the issue but removing all `.toLowerCase()` in the code you may want to remove it or explain to use lowercase tables

Error:
```
C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'forEach' of undefined
    at Query.<anonymous> (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\sequences\Query.js:92:8)
    at Protocol._parsePacket (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\roman\Desktop\realm-bot-v2\node_modules\mysql\lib\Connection.js:88:28)```

**Comment by Paultje52** [comment]
Can you share the code that made this error so I can better understand what's going on?

**Comment by Paultje52** [comment]
I saw that you made a fork of better-mysql. If that code resolves the issue, feel free to make a pull-request!

**Comment by Kaaaaii** [comment]
ok
